name: minitorch-conda-env-py312

channels:
  - conda-forge

dependencies:
  - python=3.12
  - chalk-diagram
  - colorama>=0.4.6
  - hypothesis>=6.150
  - mypy>=1.10
  - numba>=0.60
  - numpy>=2.0
  - pre-commit>=3.5
  - pytest>=8.0
  - pytest-env
  - pytest-runner
  - typing_extensions
  - colour==0.1.5
